# Generated by Django 5.0.1 on 2024-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_messages_confirmation_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(),
        ),
    ]
